disabled_rules:
- trailing_whitespace
- vertical_whitespace
- line_length
- notification_center_detachment
- unused_optional_binding

excluded:
- Pods
- Pods/

identifier_name:
  allowed_symbols: "_"
  min_length: 2
